# Generated by Django 5.1.7 on 2025-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['upload_date']},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=1, null=1, upload_to='documents/f"{author}/"'),
        ),
    ]
