# Generated by Django 5.1.7 on 2025-05-19 15:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_document_options_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=1, null=1, upload_to=blog.models.user_directory_path),
        ),
    ]
