# Generated by Django 5.1.7 on 2025-03-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=1),
            preserve_default=1,
        ),
    ]
