# Generated by Django 5.1.7 on 2025-03-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=255, null=1),
            preserve_default=1,
        ),
    ]
