# Generated by Django 5.1.7 on 2025-04-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='user_comment',
        ),
    ]
