# Generated by Django 5.1.7 on 2025-04-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
    ]
