# Generated by Django 5.1.7 on 2025-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('rating', models.FloatField(max_length=1000, null=1)),
                ('products', models.ManyToManyField(to='shopping.item')),
            ],
        ),
    ]
