# Generated by Django 5.1.7 on 2025-05-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='products',
        ),
        migrations.AddField(
            model_name='item',
            name='Seller',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.seller'),
            preserve_default=1,
        ),
    ]
