# Generated by Django 5.1.7 on 2025-05-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_remove_seller_products_item_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('rating', models.FloatField(max_length=1000, null=1)),
                ('money', models.FloatField(max_length=1000, null=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='item',
            name='Seller',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.user'),
        ),
        migrations.DeleteModel(
            name='seller',
        ),
    ]
