# Generated by Django 5.1.7 on 2025-05-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_user_alter_item_options_alter_item_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Seller',
        ),
    ]
