# Generated by Django 5.1.7 on 2025-05-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_remove_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Seller',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.user'),
            preserve_default=1,
        ),
    ]
