# Generated by Django 5.1.7 on 2025-05-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_remove_item_seller_item_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('rating', models.FloatField(max_length=1000, null=1)),
                ('money', models.FloatField(max_length=1000, null=1)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='User',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.seller'),
        ),
    ]
