# Generated by Django 5.1.7 on 2025-05-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_remove_item_user_remove_seller_money_item_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Seller',
        ),
        migrations.DeleteModel(
            name='seller',
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.user'),
            preserve_default=1,
        ),
    ]
