# Generated by Django 5.1.7 on 2025-05-19 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_rename_seller_item_seller_item_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price'], 'permissions': (('tocomment', 'towatch'),)},
        ),
    ]
