# Generated by Django 5.1.7 on 2025-05-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price'], 'permissions': (('tocomment', 'to comment on a blog'), ('towatch', 'to see a  blog'))},
        ),
    ]
