# Generated by Django 5.1.7 on 2025-05-19 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price'], 'permissions': (('to_comment', 'to comment on a blog'),)},
        ),
    ]
