# Generated by Django 5.1.7 on 2025-05-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_alter_item_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Seller',
        ),
    ]
